export const POCKET_TYPES = {
  DEBIT: 'debit',
  CREDIT: 'credit',
};

export const E = {
  INVALID_TARGET_POCKET_TYPE: 'INVALID_TARGET_POCKET_TYPE',
  INVALID_ACTIVE_POCKET_TYPE: 'INVALID_ACTIVE_POCKET_TYPE',
  NEGATIVE_BALANCE: 'NEGATIVE_BALANCE',
};
