export const SET_POCKET_ACCOUNT = 'SET_POCKET_ACCOUNT';
export const SET_POCKET_BALANCE = 'SET_POCKET_BALANCE';
export const SWAP_POCKETS = 'SWAP_POCKETS';
export const UPDATE_EXCHANGE_RATE = 'UPDATE_EXCHANGE_RATE';
export const EXCHANGE_REQUEST = 'EXCHANGE_REQUEST';
export const EXCHANGE = 'EXCHANGE';
